//The code for the Super Mario Bros theme song (with flashing colors)

void SUPERMARIOBROS() {

  displayRed();
  playNoteLength(e5, eighthNote);
  playNoteLength(e5, eighthNote);
  rest(eighthNote);
  displayOrange();
  playNoteLength(e5, eighthNote);
  rest(eighthNote);
  displayYellow();
  playNoteLength(c5, eighthNote);
  playNoteLength(e5, quarterNote);
  playNoteLength(g5, quarterNote);
  rest(quarterNote);
  displayGreen();
  playNoteLength(g4, quarterNote);
  rest(quarterNote);
  displayTeal();
  playNoteLength(c5, dottedQuarterNote);
  playNoteLength(g4, eighthNote);
  rest(quarterNote);
  displayBlue();
  playNoteLength(e4, dottedQuarterNote);
  playNoteLength(a4, quarterNote);
  playNoteLength(b4, quarterNote);
  playNoteLength(bb4, eighthNote);
  playNoteLength(a4, quarterNote);
  playNoteLength(g4, dottedEighthNote);
  playNoteLength(e5, dottedEighthNote);
  playNoteLength(g5, dottedEighthNote);
  playNoteLength(a5, quarterNote);
  playNoteLength(f5, eighthNote);
  playNoteLength(g5, eighthNote);
  rest(eighthNote);
  displayPurple();
  playNoteLength(e5, quarterNote);
  playNoteLength(c5, eighthNote);
  playNoteLength(d5, eighthNote);
  playNoteLength(b4, quarterNote);
  rest(eighthNote);
  displayPink();
  playNoteLength(c5, dottedQuarterNote);
  playNoteLength(g4, eighthNote);
  rest(quarterNote);
  displayRed();
  playNoteLength(e4, dottedQuarterNote);
  playNoteLength(a4, quarterNote);
  playNoteLength(b4, quarterNote);
  playNoteLength(bb4, eighthNote);
  playNoteLength(a4, quarterNote);
  playNoteLength(g4, dottedEighthNote);
  playNoteLength(e5, dottedEighthNote);
  playNoteLength(g5, dottedEighthNote);
  playNoteLength(a5, quarterNote);
  playNoteLength(f5, eighthNote);
  playNoteLength(g5, eighthNote);
  rest(eighthNote);
  displayOrange();
  playNoteLength(e5, quarterNote);
  playNoteLength(c5, eighthNote);
  playNoteLength(d5, eighthNote);
  playNoteLength(b4, quarterNote);
  rest(eighthNote);
  displayYellow();
  rest(quarterNote);

  //part B

  playNoteLength(g5, eighthNote);
  playNoteLength(gb5, eighthNote);
  playNoteLength(f5, eighthNote);
  playNoteLength(ds5, quarterNote);
  playNoteLength(e5, eighthNote);
  rest(eighthNote);
  displayGreen();
  playNoteLength(gs4, eighthNote);
  playNoteLength(a4, eighthNote);
  playNoteLength(c5, eighthNote);
  rest(eighthNote);
  displayTeal();
  playNoteLength(a4, eighthNote);
  playNoteLength(c5, eighthNote);
  playNoteLength(d5, eighthNote);
  rest(quarterNote);
  displayBlue();
  playNoteLength(g5, eighthNote);
  playNoteLength(gb5, eighthNote);
  playNoteLength(f5, eighthNote);
  playNoteLength(ds5, quarterNote);
  playNoteLength(e5, eighthNote);
  rest(eighthNote);
  displayPurple();
  playNoteLength(c6, eighthNote);
  rest(eighthNote);
  displayPink();
  playNoteLength(c6, eighthNote);
  playNoteLength(c6, halfNote);
  rest(quarterNote);
  displayRed();
  playNoteLength(g5, eighthNote);
  playNoteLength(gb5, eighthNote);
  playNoteLength(f5, eighthNote);
  playNoteLength(ds5, quarterNote);
  playNoteLength(e5, eighthNote);
  rest(eighthNote);
  displayOrange();
  playNoteLength(gs4, eighthNote);
  playNoteLength(a4, eighthNote);
  playNoteLength(c5, quarterNote);
  rest(eighthNote);
  playNoteLength(a4, eighthNote);
  playNoteLength(c5, eighthNote);
  playNoteLength(d5, eighthNote);
  rest(quarterNote);
  displayYellow();
  playNoteLength(eb5, quarterNote);
  rest(eighthNote);
  displayGreen();
  playNoteLength(d5, eighthNote);
  rest(quarterNote);
  displayTeal();
  playNoteLength(c5, quarterNote);
  rest(quarterNote);
  displayBlue();
  //repeat part B
  rest(quarterNote);
  playNoteLength(g5, eighthNote);
  playNoteLength(gb5, eighthNote);
  playNoteLength(f5, eighthNote);
  playNoteLength(ds5, quarterNote);
  playNoteLength(e5, eighthNote);
  rest(eighthNote);
  displayPurple();
  playNoteLength(gs4, eighthNote);
  playNoteLength(a4, eighthNote);
  playNoteLength(c5, eighthNote);
  rest(eighthNote);
  displayPink();
  playNoteLength(a4, eighthNote);
  playNoteLength(c5, eighthNote);
  playNoteLength(d5, eighthNote);
  rest(quarterNote);
  displayRed();
  playNoteLength(g5, eighthNote);
  playNoteLength(gb5, eighthNote);
  playNoteLength(f5, eighthNote);
  playNoteLength(ds5, quarterNote);
  playNoteLength(e5, eighthNote);
  rest(eighthNote);
  displayOrange();
  playNoteLength(c6, eighthNote);
  rest(eighthNote);
  displayYellow();
  playNoteLength(c6, eighthNote);
  playNoteLength(c6, halfNote);
  rest(quarterNote);
  displayGreen();
  playNoteLength(g5, eighthNote);
  playNoteLength(gb5, eighthNote);
  playNoteLength(f5, eighthNote);
  playNoteLength(ds5, quarterNote);
  playNoteLength(e5, eighthNote);
  rest(eighthNote);
  displayTeal();
  playNoteLength(gs4, eighthNote);
  playNoteLength(a4, eighthNote);
  playNoteLength(c5, quarterNote);
  rest(eighthNote);
  displayBlue();
  playNoteLength(a4, eighthNote);
  playNoteLength(c5, eighthNote);
  playNoteLength(d5, eighthNote);
  rest(quarterNote);
  displayPurple();
  playNoteLength(eb5, quarterNote);
  rest(eighthNote);
  displayPink();
  playNoteLength(d5, eighthNote);
  rest(quarterNote);
  displayRed();
  playNoteLength(c5, halfNote);
  rest(halfNote);
  displayOrange();

  //part C

  playNoteLength(c5, eighthNote);
  playNoteLength(c5, eighthNote);
  rest(eighthNote);
  displayYellow();
  playNoteLength(c5, eighthNote);
  rest(eighthNote);
  displayGreen();
  playNoteLength(c5, eighthNote);
  playNoteLength(d5, eighthNote);
  rest(eighthNote);
  displayBlue();
  playNoteLength(e5, eighthNote);
  playNoteLength(c5, eighthNote);
  rest(eighthNote);
  displayPurple();
  playNoteLength(a4, eighthNote);
  playNoteLength(g4, quarterNote);
  rest(quarterNote);
  displayPink();
  playNoteLength(c5, eighthNote);
  playNoteLength(c5, eighthNote);
  rest(eighthNote);
  displayRed();
  playNoteLength(c5, eighthNote);
  rest(eighthNote);
  displayOrange();
  playNoteLength(c5, eighthNote);
  playNoteLength(d5, eighthNote);
  playNoteLength(e5, quarterNote);
  rest(halfNote);
  displayYellow();
  playNoteLength(c5, eighthNote);
  playNoteLength(c5, eighthNote);
  rest(eighthNote);
  displayGreen();
  playNoteLength(c5, eighthNote);
  rest(eighthNote);
  displayTeal();
  playNoteLength(c5, eighthNote);
  playNoteLength(d5, eighthNote);
  rest(eighthNote);
  displayBlue();
  playNoteLength(e5, eighthNote);
  playNoteLength(c5, eighthNote);
  rest(eighthNote);
  displayPurple();
  playNoteLength(a4, eighthNote);
  playNoteLength(g4, quarterNote);
  rest(quarterNote);
  displayPink();
  playNoteLength(e5, eighthNote);
  playNoteLength(e5, eighthNote);
  rest(eighthNote);
  displayRed();
  playNoteLength(e5, eighthNote);
  rest(eighthNote);
  displayOrange();
  playNoteLength(c5, eighthNote);
  playNoteLength(e5, quarterNote);
  playNoteLength(g5, quarterNote);
  rest(quarterNote);
  displayYellow();
  playNoteLength(g4, quarterNote);
  rest(quarterNote);
  displayGreen();

  //part D

  playNoteLength(e5, eighthNote);
  playNoteLength(c5, eighthNote);
  rest(eighthNote);
  displayTeal();
  playNoteLength(g4, quarterNote);
  rest(eighthNote);
  displayBlue();
  playNoteLength(gs4, eighthNote);
  rest(eighthNote);
  displayPurple();
  playNoteLength(a4, eighthNote);
  playNoteLength(f5, eighthNote);
  rest(eighthNote);
  displayPink();
  playNoteLength(f5, eighthNote);
  playNoteLength(a4, quarterNote);
  rest(quarterNote);
  displayRed();
  playNoteLength(b4, dottedEighthNote);
  playNoteLength(a5, dottedEighthNote);
  playNoteLength(a5, dottedEighthNote);
  playNoteLength(a5, dottedEighthNote);
  playNoteLength(g5, dottedEighthNote);
  playNoteLength(f5, dottedEighthNote);
  playNoteLength(e5, eighthNote);
  playNoteLength(c5, eighthNote);
  rest(eighthNote);
  displayOrange();
  playNoteLength(a4, eighthNote);
  playNoteLength(g4, quarterNote);
  rest(quarterNote);
  displayYellow();
  playNoteLength(e5, eighthNote);
  playNoteLength(c5, eighthNote);
  rest(eighthNote);
  displayGreen();
  playNoteLength(g4, quarterNote);
  rest(eighthNote);
  displayTeal();
  playNoteLength(gs4, eighthNote);
  rest(eighthNote);
  displayBlue();
  playNoteLength(a4, eighthNote);
  playNoteLength(f5, eighthNote);
  rest(eighthNote);
  displayPurple();
  playNoteLength(f5, eighthNote);
  playNoteLength(a4, quarterNote);
  rest(quarterNote);
  displayPink();
  playNoteLength(b4, eighthNote);
  playNoteLength(f5, eighthNote);
  rest(eighthNote);
  displayRed();
  playNoteLength(f5, eighthNote);
  playNoteLength(f5, dottedEighthNote);
  playNoteLength(e5, dottedEighthNote);
  playNoteLength(d5, dottedEighthNote);
  playNoteLength(c5, halfNote);
  rest(quarterNote);
  displayPink();

  //ending

  playNoteLength(c5, dottedQuarterNote);
  playNoteLength(g4, eighthNote);
  rest(quarterNote);
  displayRed();
  playNoteLength(e4, dottedQuarterNote);
  displayOrange();
  playNoteLength(a4, dottedEighthNote);
  displayYellow();
  playNoteLength(b4, dottedEighthNote);
  displayGreen();
  playNoteLength(a4, dottedEighthNote);
  displayTeal();
  playNoteLength(ab4, dottedEighthNote);
  displayBlue();
  playNoteLength(bb4, dottedEighthNote);
  displayPurple();
  playNoteLength(ab4, dottedEighthNote);
  displayPink();
  playNoteLength(g4, sixteenthNote);
  displayRed();
  playNoteLength(fs4, sixteenthNote);
  displayWhite();
  playNoteLength(g4, twoWholeNote);
}
